src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=true)
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=true)
     */
    private $utilisateur;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $status;


    public function getId(): ?int
    {
        return $this->id;
    }

     //Ajouté dans convertir les id utilisateur en chaîne de caractères
     /**
     * Transform to string
     * 
     * @return string
     */
    public function __toString()
    {
    return (string) $this->getUtilisateur();
    return (string) $this->getStatus();
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }
    
    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getUtilisateur(): ?Users
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Users $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Data\SearchData;
use App\Entity\Carousel;
use App\Form\SearchType;
use App\Form\ArticleType;
use App\Form\CommentType;
use App\Service\StatsService;
use App\Service\PaginationService;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use phpDocumentor\Reflection\DocBlock\Tags\Author;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * Access to the list of articles in the page "Fil d'actualité" (route parameters can be constrain thanks to an inlined requierements (= regex))
     * The constraints serach for a number (\d = digit), + (i can have several number), ? (constraints is optional), 1 (default value of the parameter)
     *  
     * @Route("/main/{page<\d+>?1}", name="main")
     */
    public function index(Request $request, ArticleRepository $repository){

        // Filter Symfony / Display articles
        // I initialize my datas by creating a new instance of the class SearchData
        $search = new SearchData();
        // I said to the controller :"in $search, define page and take in the request the value corresponding to the page. 
        // If that data is not define, put 1 by default 
        $search->page = $request->get('page', 1);
        // Create a form. It uses a SearchType Class and datas $search
        // Form will manage the request passed in parameters
        $form = $this->createForm(SearchType::class, $search);

        // to retrieve the data from the search form
        $form->handleRequest($request);
    
        // I declare a findSearch() method allowing me to extract want i want in the database
        // findSearch receive the search criteria from the filter form
        $articles = $repository->findSearch($search);
                  
        return $this->render('main/index.html.twig', [
            'articles' => $articles,
            // I send the form to the view
            'form' => $form->createView(),
            // message that is displayed in case of unsuccessful search
            'message' => 'Aucun article ne correspond aux critères de recherche que vous avez indiqués !',
        ]);
    }


    /**
     * Entry point of the website (front controller)
     * 
     * @Route("/", name="home")
     */
    public function home(StatsService $statsService)
    {
        $repo = $this->getDoctrine()->getRepository(Carousel::class);

        $carousel = $repo->findAll();

        $article = new Article();

        $stats = $statsService->getStats();

        $HomeBestArticles = $statsService->getHomeArticlesStats('DESC');

        $MostCommentedArticles = $statsService->getHomeCommentsStats('DESC');

        $TotalCommentsPerPerson = $statsService->getHomeCommentsStatsPerPerson('DESC');

        return $this->render('main/home.html.twig', [
            'carousel' => $carousel,
            'article' => $article,
            'stats' => $stats,
            'HomeBestArticles' => $HomeBestArticles,
            'MostCommentedArticles' => $MostCommentedArticles,
            'TotalCommentsPerPerson' => $TotalCommentsPerPerson
        ]);
    }

    /**
     * Create an new article or modify existing article in the same function (page "fil d'actualité" and navbar menu "Publier")
     * 
     * @Route("/main/new", name="main_create")
     * @Route("/main/{id}/edit", name="main_edit")
     * @IsGranted("ROLE_EDITOR")
     * 
     */
    public function form(Article $article = null, Request $request, EntityManagerInterface $manager)
    {

        $user = $this->getUser();

        // If there is no article, I can create a new article in page "Fil d'actualité". 
        // For that I create a new instance of class Article if the article doesn't already exist
        if(!$article){
            $article = new Article();
        }

        // create the form
        $form = $this->createForm(ArticleType::class, $article);
        // dd($form);

        $form->handleRequest($request);

        // isSubmitted and isValid are methods of class Form (check step)
        if($form->isSubmitted() && $form->isValid()) {
            if(!$article->getId()){
            //  other information that I want to give to the article in addition to those contained in the form
            $article->setCreatedAt(new \DateTime());
            $article->setUtilisateurs($user);
        }
        else{
            $article->setUpdatedAt(new \DateTime());
        }

            // to prepare manager to persist
            $manager->persist($article);
            // the manager send the request to store my article in database
            $manager->flush();

            $this->addFlash(
                'success',
                "Merci ! votre action a bien été prise en compte par le système."
                );
            
            // Redirect user to the route name 'main'
            return $this->redirectToRoute('main');
        }
            return $this->render('main/create.html.twig', [
            'article' => $article,
            // To display my form in the view, I send to TWIG the result of the function createView() 
            // form object is a complex object with many methods and TWIG doesn't want to receive a complex object.
            'formArticle' => $form->createView(),
            // to change the text of the validation button
            'editMode'=> $article->getId()!== null
            ]);
    }


    // /**
    // * @Route("/main/new", name="main_create")
    // */
    // public function create(Request $request, EntityManagerInterface $manager)
    // {
    //     $article = new Article();

    //     $form = $this->createForm(ArticleType::class, $article);

    //     $form->handleRequest($request);

    //     dump($article);

    //     if($form->isSubmitted() && $form->isValid()) {

    //         $article->setCreatedAt(new \DateTime());


    //         $manager->persist($article);
    //         $manager->flush();

    //         return $this->redirectToRoute('main_show', ['id' => $article->getId()]);
    //     }

    //     return $this->render('main/create.html.twig', [
    //         'formArticle' => $form->createView()
    //         ]);(article.comments | length) - (
    // }



    /**
     * //Pour montrer un article qui contient un formulaire de commentaire permettant d'ajouter des commentaires
     * 
     * @Route("/main/{id}", name="main_show")
     * 
     */
    public function show($id, Request $request, EntityManagerInterface $manager)
    {
        // On récupère l'article correspondant à l'id sélectionné
        $article = $this->getDoctrine()->getRepository(Article::class)->findOneBy(['id' => $id]);

        // $article = $this->getDoctrine()->getRepository(Article::class)->findOneBy([
        //     'id' => $id,
        // ]);
        

        // On récupère les commentaires validés de l'article
        $commentaires = $this->getDoctrine()->getRepository(Comment::class)->findBy(['article' => $article, 'status' => "Validé"],['created_at' => 'desc']);
        dump($commentaires);
        // die();
       


        if(!$article){
            throw $this->createNotFoundException("L'article recherché n'existe pas");
        }

        //Instancier l'entité commentaire
        $comment = new Comment();

        $user = $this->getUser();


        //Créer l'objet formulaire
        $form = $this->createForm(CommentType::class, $comment);

        //Récupération des données saisies
        $form->handleRequest($request);

        //Vérifier l'envoi du formulaire et si les données sont valides
        if($form->isSubmitted() && $form->isValid()) {

            //Le formulaire a été envoyé et les données sont valides

            $comment->setArticle($article)
                    ->setCreatedAt(new \DateTime())
                    ->setAuthor($this->getUser()->getPublicName())
                    ->setUtilisateur($user)
                    ->setStatus("Non validé");


        //On hydrate l'objet en y ajoutant les données  
            $manager->persist($comment);
        //On écrit dans la BDD
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire à bien été pris en compte !"
            );
        }

        $repo = $this->getDoctrine()->getRepository(Article::class);

        $article = $repo->find($id);

        return $this->render('main/show.html.twig', [
            'article' => $article,
            'commentForm' => $form->createView(),
            'commentaires' => $commentaires
        ]);
    }

}
   

templates/main/_article.html.twig
 <hr>
  <div class="col-md-9 ml-5 bg-warning
            
{% if app.user %}
{{ app.user.bgColor }}
{% else %}

{% endif %}
">
    {% if article.comments | length > 0 %}
    {# {% if comment.status is same as ("Validé")  %} #}
            <div class="float-right mr-2 btn btn-success">
        {% include 'template_parts/_rating.html.twig' with {'rating' : article.AvgRatings} %}
         <br>
         {# {% set commentaires = pagination %} #}
         {# {% if article.comments.status is same as ("Validé")  %} #}
    {# <p class="mt-2 mb-1" style="font-size: 1.2em;"><strong>{{ article.comments | length }}</strong> avis</p> #}
        {# <p class="mt-2 mb-1" style="font-size: 1.2em;">{{ stats.validatedCommentCount }}<strong></strong> avis</p> #}
        {# {% endif %} #}
            </div>
    {% else %}
         {% if app.user %}
         {# {{dump(app.user)}} #}
        <a href="{{ path('main_show', {'id' : article.id}) }})" class="btn btn-success btn-lg float-right ml-2 mr-2" style="color:yellow; text-shadow: 4px 6px 8px black;"><h4><b>Donner mon avis !</b></h4></a> 
         {% endif %} 
    {% endif %}

<h2><b>{{ article.title }}</b></h2>
    <h4 class="metadata mt-3"><i>Publié le {{ article.createdAt | date ('d/m/Y') }} à {{ article.createdAt | date ('H:i') }} par <strong>{{ article.utilisateurs }}</strong>
    {% if article.updatedAt is not null %}
    <span style="font-size: 0.8em; color: blue;">- Modifié le {{ article.updatedAt | date ('d/m/Y') }} à {{ article.updatedAt | date ('H:i') }}</span></i></h4>
    {% else %}
    
    {% endif %}
    <h4 class="metadata mt-3"><i>Catégorie : <h2 class="badge badge-primary" style="font-size: 1em;">{{ article.category.title }}</h2></i></h4>
    <h4 class="metadata"><i>Contenu libre : <h2 class="badge badge-success text-light" style="font-size: 1em;">{{ ((2000*100) / (article.content | length)) | number_format(0, '.', ',') }}%</h2></i></h4>
        <div class="content">
        <img src="{{ article.image }}" alt="image" class="float-left img-fluid mb-2"  style="margin-right: 1rem;">
        {# <p>{{ article.content |slice(0,1800)|raw }}</p> #}
        <p  style="text-align: justify">{{ article.content|slice(0,2000)|raw }} .......</p>
       {% if app.user %}
        <p style="color: blue; font-size: 1.5em">Il vous reste <b>{{ (100 - ((2000*100) / (article.content | length))) | number_format(0, '.', ',') }}%</b> de cet article à lire ...</p>
        <a href="{{ path('main_show', {'id' : article.id}) }})" class="btn btn-primary" style="font-size: 1.5em;"><i class="fas fa-eye"></i><b> Lire la suite</b></a>
        {% else %}
        <p style="color: red; font-size: 1.5em">Il vous reste <b>{{ (100 - ((2000*100) / (article.content | length))) | number_format(0, '.', ',') }}%</b> de cet article à lire ...</p>
        {# <a href="{{path('security_login')}}" class="btn btn-danger mt-2" style="font-size: 1.5em;"><b>S'inscrire pour lire la suite <i style="color: yellow;">({{ (100 - ((2000*100) / (article.content | length))) | number_format(0, '.', ',') }}%)</i></b></a> #}
        <a href="{{path('security_login')}}" class="btn btn-danger" style="font-size: 1.5em;"><b> La suite est réservée aux abonnés !</b></a>
       {% endif %}
        </div>
      <hr>

          </div>
</div>

templates/main/_filter.html.twig
<div class="accordion mb-5 filter" id="accordionExample">
        <div class="card">
            <div class="card-header bg-dark text-center" id="headingThree">
                <h5 class="mb-0">
                    <b><button class="btn btn-link text-light" type="button" data-toggle="collapse" data-target="#collapseThree" 
                    aria-expanded="true" aria-controls="collapseThree" style="text-decoration: none"><i class="fas fa-filter text-light mr-2"></i> FILTRES</b></button>
                </h5>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body bg-secondary">
{{ form_start(form, {attr: {class: 'filter'}}) }}
    <h4 class="mt-3 p-1 alert alert-primary text-center"><b>TITRE</b></h4>
    <div>{{ form_row(form.q) }}</div>
    <h4 class="mt-3 p-1 alert alert-primary text-center"><b>THEMES</b></h4>
    <div class="text-light">{{ form_row(form.categories) }}</div>
    {# <h4 class="p-1 alert alert-primary text-center"><b>NOTE</b></h4>
    <div class="row d-flex justify-content-around">
        <div class="col-md-6 alert alert-danger">
            {{ form_row(form.min) }}
        </div>
        <div class="col-md-6 alert alert-success">
            {{ form_row(form.max) }}
        </div>
    </div> #}
    <h4 class="p-1 alert alert-primary text-center"><b>AUTEUR</b></h4>
    <div>{{ form_row(form.auteur) }}</div>

<button type="submit" class="btn btn-primary p-3 w-100 mb-5 border-light"><i class="fas fa-filter"></i><b> FILTRER</b></button>

{{ form_end(form) }}

</div>
</div>
</div>
</div>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue !{% endblock %}

{% block body %}

	<div class="ml-5 mt-2 mb-5">

		<div class="row">
			<div class="col-md-3 filter">
				{% include 'main/_filter.html.twig' with {form: form} only %}
			</div>

			<div class="col-md-8 ml-3 px-5 py-0 border-left
					
					            {% if app.user %}
					            {{ app.user.bgColor }}
					            {% else %}
					
					            {% endif %}
					            ">

				<h1 class="text-center my-2 filActu alert alert-primary">
					<b>FIL D'ACTUALITE</b> 
				</h1>
				{% if is_granted('ROLE_EDITOR') %}
				<h4><a href="{{ path('main_create') }}" class="badge badge-warning text-dark text-right border border-dark p-3 mt-2"><i class="fas fa-plus"></i> AJOUTER UN ARTICLE</a></h4>
				{% endif %}

				{% if articles | length > 0 %}

				{% for articles in articles %}


					<hr class="mb-4">
					{% if articles.comments | length > 0 %}

						<div class="float-right mr-2 btn btn-success">
							{% include 'template_parts/_rating.html.twig' with {'rating' : articles.AvgRatings} %}
							<br>
						</div>
					{% else %}

						{% if app.user %}

							<a href="{{ path('main_show', {'id' : articles.id}) }}" class="btn btn-success btn-lg float-right ml-2 mr-2" style="color:yellow; text-shadow: 4px 6px 8px black;">
								<h4>
									<b>Donner mon avis !</b>
								</h4>
							</a>
						{% endif %}

					{% endif %}


					<h2>
						<b>{{ articles.title }}</b>
					</h2>
					<h4 class="metadata mt-3">
					{% if is_granted('ROLE_EDITOR') %}
						<h4><a href="{{ path('main_edit', {'id' : articles.id}) }}" class="badge badge-warning text-dark text-right border border-dark p-3 mb-2"><i class="fas fa-edit"></i> MODIFIER CET ARTICLE</a></h4>
					{% endif %}
						<i>Publié le
							{{ articles.createdAt | date ('d/m/Y') }}
							à
							{{ articles.createdAt | date ('H:i') }}
							par
							<strong>{{ articles.utilisateurs }}</strong>
							{% if articles.updatedAt is not null %}
								<span style="font-size: 0.8em; color: blue;">- Modifié le
									{{ articles.updatedAt | date ('d/m/Y') }}
									à
									{{ articles.updatedAt | date ('H:i') }}</span>
							</i>
						</h4>
						{% else %}

					{% endif %}
					<h4 class="metadata mt-3">
						<i>Catégorie :
							<h2 class="{{ articles.category.color }} text-light" style="font-size: 1em;">{{ articles.category.title }}</h2>
						</i>
					</h4>
					<h4 class="metadata">
						<i>Contenu libre :
							<h2 class="badge badge-success text-light" style="font-size: 1em;">{{ ((2000*100) / (articles.content | length)) | number_format(0, '.', ',') }} %</h2>
						</i>
					</h4>
					<div class="content mb-5">
						<img src="{{ articles.image }}" alt="image" class="float-left img-fluid mb-2" style="margin-right: 1rem;">

						<p style="text-align: justify">{{ articles.content|slice(0,2000)|raw }} .......</p>
						{% if app.user %}
							<p style="color: blue; font-size: 1.2em">Il vous reste
								<b>{{ (100 - ((2000*100) / (articles.content | length))) | number_format(0, '.', ',') }} %</b> de cet article à lire ...</p>
							<a href="{{ path('main_show', {'id' : articles.id}) }})" class="btn btn-primary" style="font-size: 1.4em;">
								<i class="fas fa-eye"></i>
								<b>
									Lire la suite</b>
							</a>
						{% else %}
							<p style="color: red; font-size: 1.2em">Il vous reste
								<b>{{ (100 - ((2000*100) / (articles.content | length))) | number_format(0, '.', ',') }} %</b> de cet article à lire ...</p>
							<a href="{{path('security_login')}}" class="btn btn-danger" style="font-size: 1.4em;">
								<b>
									La suite est réservée aux abonnés !</b>
							</a>
						{% endif %}
					</div>


                    
				{% endfor %}

				{% else %}
					<div class="container mt-5 mb-5">
						<div class="col-md-12">
							<div class="alert alert-danger border border-dark text-center">
								<p class="mt-5 text-danger" style="font-size: 2rem;"><i class="fas fa-times-circle text-danger"></i> {{ message }}</p>
								{# <div class="mt-5 mb-5"> #}
								{# <a href="{{ path('home') }}" class="badge badge-success border border-dark p-3 mr-5" style="font-size: 1rem;">RETOUR ACCUEIL</a>
								<a href="{{ path('products') }}" class="badge badge-warning border border-dark p-3" style="font-size: 1rem;">RETOUR BOUTIQUE</a> #}
								{# </div> #}
							</div>
						</div>
					</div>
        		{% endif %}

                <hr>
                <div class="d-flex justify-content-center mt-5">
                	{{ knp_pagination_render(articles) }}
                </div>
			</div>
		</div>
   
 </div>

	{% endblock %}

templates/main/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lire un article
{% endblock %}


{% block body %}

	<article
		class="container mt-5 mb-5
			
			{% if app.user %}
			{{ app.user.bgColor }}
			{% else %}
			
			{% endif %}
			">

		{% if article.comments | length > 0 %}
			<div class="float-right btn btn-success">
				{% include 'template_parts/_rating.html.twig' with {'rating' : article.AvgRatings} %}
				<br>
				<p class="mt-2 mb-1" style="font-size: 1.2em;">
					<strong>{{ commentaires | length }}</strong>
					avis</p>
			</div>
		{% else %}
			<a href="#avis" class="btn btn-success btn-lg float-right ml-2 mr-2" style="color:yellow; text-shadow: 4px 6px 8px black;">
				<h4>
					<b>Donner mon avis !</b>
				</h4>
			</a>
		</div>
	{% endif %}
	<h2>
		<b>{{ article.title }}</b>
	</h2>
	<h4 class="metadata">
		<i>Publié le
			{{ article.createdAt | date ('d/m/Y') }}
			à
			{{ article.createdAt | date ('H:i') }}
			par
			<strong>{{ article.utilisateurs }}</strong>
			{% if article.updatedAt is not null %}
				<span style="font-size: 0.8em; color: blue;">- Modifié le
					{{ article.updatedAt | date ('d/m/Y') }}
					à
					{{ article.updatedAt | date ('H:i') }}</span>
		</i>
	</h4>
		    {% else %}

	{% endif %}
	<h4 class="metadata">
		<i>Catégorie :
			<h2 class="badge badge-primary" style="font-size: 1em;">{{ article.category.title }}</h2>
		</i>
	</h4>
	<div class="content">
		<img
		src="{{ article.image }}" alt="image" class="float-left img-fluid" style="width: 600px; height:300px; padding-right: 20px;">
		{# <p>{{ article.content |slice(0,1800)|raw }}</p> #}
		<p style="text-align: justify">{{ article.content | raw }}</p>
		<hr style="border: 1px solid blue;" class="mt-5 mb-5" id="avis">
		{# <a href="" class="btn btn-primary mt-5 mb-4 mr-5 float-xl-none float-right"><i class="fa fa-comment" aria-hidden="true"></i> Ajouter un commentaire</a> #}
		{# <a href="{{path('main')}}" class="btn btn-primary mt-4 mb-5 mr-5 float-xl-none float-right" style="font-size: 1.6em;"><i class="fa fa-reply-all" aria-hidden="true"></i> <b>Retour au fil d'actualité</b></a> #}
		{# {% set comment = article.comments %} #}

		{% set comment = article.commentFromAuthor(app.user) %}

		{# {{dump(app.user)}}
		    {{dump(comment)}}
		    #}

			{% if comment is not null %}
				<div
				class="container col-8 bg-secondary float-left border border-dark text-light mt-4 mb-4"> {# <h2 class="mt-2" style="color:white; text-shadow: 4px 6px 8px black;"><b><img src="{{app.user.avatar}}" style="max-width:45px; border-radius:50%"> VOTRE AVIS :<h4 class="float-right mt-2">{{ comment.createdAt | date ('d/m/Y') }} à {{ comment.createdAt | date ('H:i') }}</h4</b></h2> #}
				<h2 class="mt-2" style="color:white; text-shadow: 4px 6px 8px black;">
					<b><img src="{{app.user.avatar}}" style="max-width:45px; border-radius:50%">
						Votre avis :<h4 class="float-right mt-2">{{ comment.createdAt | date ('d/m/Y') }}
							à
							{{ comment.createdAt | date ('H:i') }}</h4</b>
					</h2>
					<hr style="border: none; border-bottom: 2px solid #fff;">
					<blackquote>
						<h4 class="mt-2 mb-4">
							<i>"{{comment.content}}"</i>
						</h4>
					</blackquote>
					<h4 class="py-2" style="color:white; text-shadow: 4px 6px 8px black;">
						<strong>VOTRE NOTE :</strong>
						{% include 'template_parts/_rating.html.twig' with {'rating': comment.rating} %}</h4>
				</div>
			{% else %}
				<div class="alert alert-dark mt-5 mb-4">
					<h1 class="alert-heading mb-3">
						<i class="fa fa-comment" aria-hidden="true"></i>
						Réagissez à cet article !</h1>
					{{ form_start(commentForm) }}
					{{ form_widget(commentForm) }}
					<button type="submit" class="btn btn-success">
						<b>Poster !</b>
					</button>
					{{ form_end(commentForm) }}
				</div>
			{% endif %}

			<a href="{{path('main')}}" class="btn btn-primary mt-4 mb-3 mr-5 float-xl-none float-right" style="font-size: 1.6em;">
				<i class="fa fa-reply-all" aria-hidden="true"></i>
				<b>Retour au fil d'actualité</b>
			</a>
		</article>
		<section class="alert alert-warning" id="commentaires">

			{% if article.comments | length > 0 %}
				{# {% if comment.status is same as ("Validé")  %} #}
				<h2 class="mb-3 text-center text-dark mt-5 mb-5">
					<strong>COMMENTAIRES DE NOS LECTEURS</strong>
				</h2>

				<div class="container col-10 alert bg-primary text-light mb-4">
					<h1 class="alert-heading text-center">
						<div class="row align-items-center">
							<div class="col">
								<b style="text-shadow: 6px 8px 8px black;">NOTE DE L'ARTICLE</b>

							</div>
							<div class="col">
								<span class="rating mt-2">
									{% include 'template_parts/_rating.html.twig' with {'rating' : article.AvgRatings} %}
								</span>
								<br>
								{# {% for comment in commentaires %} #}
								<div>
									<small>Evaluation sur
										<strong>{{commentaires | length }}</strong>
										avis !</small>
								</div>
								{# {% endfor %} #}
							</div>
						</div>
					</h1>
				</div>
				{# {% endif %} #}
			{% else %}
				<h2 class="m-3 mb-3 text-center">
					<strong>Commentaires des lecteurs</strong>
				</h2>
				<div class="container col-7 bg-danger text-light">
					<h2 class="mt-5 mb-5 text-center p-5">
						<i>Cette article n'a pas encore reçu de commentaire !</i>
                    </h2>
						<br>
					</div>
			{% endif %}


				{% for comment in commentaires %}
					{# {% if comment.status is same as ("Validé")  %}  #}

					<div class="container col-4 alert bg-success text-light rounded mb-3 py-3 px-3">
						<img src="{{ comment.utilisateur.avatar }}" style="max-width:45px; border-radius:50%">
						<i>{{ comment.createdAt | date ('d/m/Y') }}
							à
							{{ comment.createdAt | date ('H:i') }}
							par
							<strong>
								<u>{{ comment.author }}</u>
							</i>
						</strong>
						<hr style="border: none; border-bottom: 1px solid #fff;">
						<blockquote class="mt-3">
							<h5>
								<i>"{{comment.content}}"</i>
							</h5>
						</blockquote>
						<strong style="font-size: 1.5em; text-shadow: 6px 6px 4px black;">
							<i>NOTE DE L'ARTICLE :</i>
						</strong>
						{% set rating = comment.rating %}
						{% include 'template_parts/_rating.html.twig' with {'rating' : comment.rating} %}

					</div>
				{% endfor %}


			</section>
{% endblock %}